# Site settings
title: 七姑娘日记
header-img: "../img/header/Home5.jpg"
tagline: "cn"  
description: "七姑娘|七姑娘日记"
baseurl: ""
url: "https://julysxy.com"

# About/contact
owner: 
  name: "七姑娘"
  email: julyfly321520@163.com
  bio: "七姑娘日记"

# Data
gavatar: img/favicon.png
favicon: img/favicon.ico

douban_username:
twitter_username:
github_username: JulyShi
facebook_username: 
weibo_username:
zhihu_username: julysxy
linkedin_username: Shi Xiangyang
tw_username: shixiangyang

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "七姑娘"
      header-img: "img/header/Home6.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 


# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation


# CSS
sass:
    sass_dir: _sass
    style: compressed
    
include: [_pages]